---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Repository_at_start/Repository_at_start.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/244977/articles/324602/master/file/figures/Repository_at_start/Repository_at_start.png"
    folder_url: "/users/244977/articles/324602/master/folder/figures/Repository_at_start"
