---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Figure_iris/Figure_iris.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/244977/articles/324602/master/file/figures/Figure_iris/Figure_iris.png"
